### ISSUE TITLE
Cleanup doesn't work outside of the current directory

### ISSUE THREAD

**Issue by dominik0711** [ragingwind/grunt-crisper#3]
Using the parameter **cleanup: true**, I'll get the following warning

`Warning: Cannot delete files outside the current working directory`

The vulcanized.html file is generated to **!deploy/web** and isn't deleted there after cripser clean task.

This is my structure:

<img width="201" alt="structure" src="https://cloud.githubusercontent.com/assets/1011188/12758248/ff386684-c9db-11e5-83ca-40eb5d32301d.png">

**Comment by ragingwind** [comment]
Fixes by https://github.com/ragingwind/grunt-crisper/commit/11b0232d85d980aec1ef7b698f172ce6812c8383
