### ISSUE TITLE
generated path to javascript file is invalid. 

### ISSUE THREAD

**Issue by ermish** [ragingwind/grunt-crisper#4]
When I run crisper, the file path is getting set to the top level directory instead of the current location of the new js file. 
### Example

`/my/sub/folder/test.html` produces `/my/sub/folder/test.js` 
However, the html's script path points to `src="test.js"` instead of `src="/my/sub/folder/test.js"`

**Comment by ragingwind** [comment]
That is right. this generator drop both files html/js in same path. ~~relative path between html and js~~

**Comment by ermish** [comment]
I'm currently running `crisper` on multiple files. I was able to modifiy the path using `jsFileName` for a single file. Is there a way to do this with a variable for the name for a file set?  Ex. jsFileName: '/my/sub/folder/*.js' 

As an alternative, a new option for setting file paths would be helpful.

**Comment by ragingwind** [comment]
It is just a plugin for crisper. you should ask https://github.com/PolymerLabs/crisper for that. setting file paths will be supported soon thanks.

**Comment by ragingwind** [comment]
Sorry for confusing, you can pass 'jsFileName' options to `crisper` what you want. see https://github.com/ragingwind/grunt-crisper/blob/master/tasks/crisper.js#L55

**Comment by ermish** [comment]
Oops, my mistake. I thought I was on the `crisper` repo. Thanks @ragingwind!
